# Generated by Django 4.0 on 2024-01-18 11:22

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('icloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localmedia',
            name='originTest',
            field=simplepro.components.fields.VideoField(blank=True, max_length=255, null=True, verbose_name='视频原始文件'),
        ),
    ]
