# Generated by Django 4.0 on 2024-01-18 11:24

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('icloud', '0002_localmedia_origintest'),
    ]

    operations = [
        migrations.AddField(
            model_name='localmedia',
            name='thumbTest',
            field=simplepro.components.fields.VideoField(blank=True, max_length=255, null=True, verbose_name='缩略图(测试)'),
        ),
        migrations.AlterField(
            model_name='localmedia',
            name='originTest',
            field=simplepro.components.fields.VideoField(blank=True, max_length=255, null=True, verbose_name='视频原始文件(测试)'),
        ),
    ]
