# Generated by Django 4.0 on 2024-03-15 15:26

from django.db import migrations, models
import simplepro.lib.pkHelper


class Migration(migrations.Migration):

    dependencies = [
        ('icloud', '0005_remove_localmedia_thumbtest_alter_localmedia_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='id',
            field=models.CharField(default=simplepro.lib.pkHelper.uuid_generator, editable=False, max_length=48),
        ),
        migrations.AddField(
            model_name='album',
            name='remark',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='小备注/标签'),
        ),
        migrations.AddField(
            model_name='appleid',
            name='remark',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='小备注/标签'),
        ),
        migrations.AddField(
            model_name='imedia',
            name='remark',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='小备注/标签'),
        ),
        migrations.AddField(
            model_name='localmedia',
            name='remark',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='小备注/标签'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='appleid',
            name='id',
            field=models.CharField(default=simplepro.lib.pkHelper.uuid_generator, editable=False, max_length=48, primary_key=True, serialize=False),
        ),
    ]
