# Generated by Django 4.0 on 2024-03-16 23:23

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('icloud', '0006_album_id_album_remark_appleid_remark_imedia_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imedia',
            name='albums',
            field=simplepro.components.fields.ManyToManyField(blank=True, related_name='medias', to='icloud.Album', verbose_name='相册'),
        ),
    ]
