# Generated by Django 4.0 on 2024-03-16 23:52

from django.db import migrations, models
import simplepro.lib.pkHelper


class Migration(migrations.Migration):

    dependencies = [
        ('icloud', '0007_alter_imedia_albums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(default=simplepro.lib.pkHelper.uuid_generator, editable=False, max_length=48, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='标题'),
        ),
    ]
