# Generated by Django 4.0 on 2024-03-17 01:28

from django.db import migrations
import simplepro.components.fields.input_password_field


class Migration(migrations.Migration):

    dependencies = [
        ('icloud', '0008_alter_album_id_alter_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleid',
            name='passwd',
            field=simplepro.components.fields.input_password_field.PasswordInputField(blank=True, max_length=48, null=True, verbose_name='密码'),
        ),
    ]
