# Generated by Django 4.0 on 2024-03-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icloud', '0010_album_appleid_imedia_appleid_localmedia_appleid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'iCloud相册', 'verbose_name_plural': 'iCloud相册'},
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('name', 'appleId'), name='unique_name_appleId'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('id', 'appleId'), name='unique_id_appleId'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('name', 'id'), name='unique_name_id'),
        ),
    ]
